// Common admin/backoffice endpoint paths. Used to seed the Scan tab when the
// user wants to discover an admin API surface as an alternative route in
// when the normal client-facing endpoint is blocked, rate-limited, or
// otherwise doesn't behave as needed. Not exhaustive — the path list in the
// Scan tab is fully editable.
export const ADMIN_PATH_WORDLIST: string[] = [
  // Generic admin roots
  "admin",
  "administrator",
  "admin-api",
  "admin_api",
  "adminapi",
  "backoffice",
  "back-office",
  "internal",
  "internal-api",
  "manage",
  "management",
  "staff",
  "ops",
  "console",
  "cp",
  "control-panel",
  "controlpanel",
  "dashboard",
  "moderator",
  "mod",
  "root",
  "superuser",
  "super-admin",
  "superadmin",

  // API-prefixed variants
  "api/admin",
  "api/administrator",
  "api/internal",
  "api/manage",
  "api/management",
  "api/staff",
  "api/ops",
  "api/backoffice",
  "api/moderator",
  "api/v1/admin",
  "api/v2/admin",
  "api/v1/internal",
  "api/v1/manage",

  // Nested admin routes
  "admin/login",
  "admin/dashboard",
  "admin/users",
  "admin/user",
  "admin/config",
  "admin/settings",
  "admin/api",
  "admin/panel",
  "admin/console",
  "admin/reports",
  "admin/orders",
  "admin/system",
  "admin/health",
  "admin/status",
  "admin/tools",
  "admin/debug",

  // Framework/CMS defaults
  "wp-admin",
  "wp-json/wp/v2/users",
  "administrator/index.php",
  "django-admin",
  "_admin",
  "sys-admin",
  "sysadmin",

  // Service-management style
  "service-api/admin",
  "service-api/internal",
  "games-frame/admin",
  "games-frame/service-api/admin",
];

// Game-engine API paths — scan these relative to the service-api base URL
// (e.g. https://host/games-frame/service-api) to find non-mutating state
// query endpoints that reveal game data without registering any action.
export const GAME_API_WORDLIST: string[] = [
  // ── PascalCase (matches MakeAction naming convention) ──
  "GetState",
  "GetGameState",
  "GetGame",
  "GetGameInfo",
  "GetInfo",
  "GetSession",
  "GetCurrentGame",
  "GetCurrentState",
  "GetRound",
  "GetRoundState",
  "GetUserGame",
  "GetLastGame",
  "GetResult",
  "GetResults",
  "GetHistory",
  "GetConfig",
  "GetBalance",
  "GetPreview",
  "StartGame",
  "InitGame",
  "GameState",
  "GameInfo",
  "GameSession",
  "GameResult",
  "GameHistory",
  "CurrentGame",
  "CurrentState",
  "CurrentRound",
  "RoundResult",
  "Status",
  "State",
  "Info",
  "Round",
  "Game",
  "Session",
  "Result",
  "Results",
  "Preview",
  "Balance",
  "History",
  "Config",

  // ── camelCase variants ──
  "getState",
  "getGameState",
  "getGame",
  "getGameInfo",
  "getInfo",
  "getSession",
  "getCurrentGame",
  "getCurrentState",
  "getRound",
  "getUserGame",
  "getLastGame",
  "getResult",
  "getResults",
  "getHistory",
  "getConfig",
  "getBalance",
  "startGame",
  "initGame",
  "gameState",
  "gameInfo",
  "gameSession",
  "currentGame",
  "currentState",

  // ── kebab-case variants ──
  "get-state",
  "game-state",
  "game-info",
  "game-session",
  "current-game",
  "round-result",
  "get-result",
  "get-history",
  "get-balance",
  "start-game",
  "init-game",

  // ── snake_case variants ──
  "get_state",
  "game_state",
  "game_info",
  "current_game",
  "round_result",
  "get_result",
  "get_history",
  "get_balance",
  "start_game",
  "init_game",

  // ── Sibling paths (same host, different service path) ──
  "service-api/GetState",
  "service-api/GetGame",
  "service-api/GetInfo",
  "service-api/GameState",
  "service-api/Status",
];
